base_scenery:
    resource: "@BaseBundle/Controller/SceneryController.php"
    type:     annotation

base_surrounding:
    resource: "@BaseBundle/Controller/SurroundingController.php"
    type:     annotation

base_component:
    resource: "@BaseBundle/Controller/ComponentController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

base:
    resource: "@BaseBundle/Resources/config/routing.yml"
    prefix:   /

default:
    resource: "@BaseBundle/Controller/"
    type:      annotation
    prefix:   /

component:
    resource: "@BaseBundle/Controller/"
    type:      annotation
    prefix:   /