<?php

namespace BaseBundle\Repository;

/**
 * SceneryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SceneryRepository extends \Doctrine\ORM\EntityRepository
{
}
