<?php

namespace BaseBundle\Repository;

/**
 * SurroundingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurroundingRepository extends \Doctrine\ORM\EntityRepository
{
}
